
<?php echo $this->render('titulo.phtml'); ?>

<div id="sys_conteudo">

    <div id ="painel_principal">

        <div id="cpanel">

		<div style="float:left;">
			<div class="icon">
				<a href="<?php echo BASE_URL.'/diasletivos'; ?>">
                                    <img alt=""  src="<?php echo BASE_URL.'/public/templates/system/imagens/agenda.png'; ?>" align="middle" border="0" />
                                            <span>Dias Letivos</span>
                                </a>
                        </div>
		</div>
    <div style="float:left;">
		<div class="icon">
				<a href="<?php echo BASE_URL.'/horarios'; ?>">
                                    <img alt=""  src="<?php echo BASE_URL.'/public/templates/system/imagens/horarios.png'; ?>" align="middle" border="0" />
                                            <span>Hórários de Aulas</span>
                                </a>
                        </div>
		</div>
    <div style="float:left;">
    <div class="icon">
				<a href="<?php echo BASE_URL.'/curso'; ?>">
                                    <img alt=""  src="<?php echo BASE_URL.'/public/templates/system/imagens/cursos.png'; ?>" align="middle" border="0" />
                                            <span>Cursos</span>
                                </a>
                        </div>
		</div>
    <div style="float:left;">
    <div class="icon">
				<a href="<?php echo BASE_URL.'/disciplina'; ?>">
                                    <img alt=""  src="<?php echo BASE_URL.'/public/templates/system/imagens/disciplinas.png'; ?>" align="middle" border="0" />
                                            <span>Disciplinas</span>
                                </a>
                        </div>
		</div>
    <div style="float:left;">
    <div class="icon">
				<a href="<?php echo BASE_URL.'/professor'; ?>">
                                    <img alt=""  src="<?php echo BASE_URL.'/public/templates/system/imagens/professores.png'; ?>" align="middle" border="0" />
                                            <span>Professors</span>
                                </a>
                        </div>
		</div>
    <div style="float:left;">
    <div class="icon">
				<a href="<?php echo BASE_URL.'/turmadisciplina'; ?>">
                                    <img alt=""  src="<?php echo BASE_URL.'/public/templates/system/imagens/turma_disciplinas.png'; ?>" align="middle" border="0" />
                                            <span>Disciplinas por Turmas</span>
                                </a>
                        </div>
		</div>
    <div style="float:left;">
    <div class="icon">
				<a href="<?php echo BASE_URL.'/gradehorario'; ?>">
                                    <img alt=""  src="<?php echo BASE_URL.'/public/templates/system/imagens/gerar.png'; ?>" align="middle" border="0" />
                                            <span>Grades de Horários</span>
                                </a>
                        </div>
		</div>

	  </div>
    </div>
</div>